version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/cv-web-frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/cv-web-backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
