
volumes:
  grafana-storage:

services:
  # ******************
  # Grafana
  # ******************
  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - tempo
      - loki

  # ******************
  # Prometheus
  # ******************
  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=exemplar-storage
      - --web.enable-remote-write-receiver
    volumes:
      - ./grafana/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./grafana/alert-rules.yml:/etc/prometheus/alert-rules.yml
    ports:
      - "9090:9090"

  # ******************
  # Alertmanager
  # ******************
  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./grafana/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  # ******************
  # Tempo (Tracing)
  # ******************
  tempo:
    image: grafana/tempo:main-4338f18
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3200"  # Tempo HTTP API
      - "4317"  # OTLP gRPC
      - "4318"  # OTLP HTTP
    volumes:
      - ./grafana/tempo.yml:/etc/tempo.yaml

  # ******************
  # Loki (Logs)
  # ******************
  loki:
    image: grafana/loki:3.4.1
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100"
      - "9096"
    volumes:
      - ./grafana/loki.yml:/etc/loki/local-config.yaml