---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cv-web-frontend-dev
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cv-web-dev-ns
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: ghcr.io/andrislapins/helm-charts
    chart: cv-web-frontend
    targetRevision: 0.0.6
    helm:
      valueFiles:
        - ../cv-web-frontend-values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
