---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cv-web-backend-dev
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cv-web-dev-ns
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: ghcr.io/andrislapins/helm-charts
    chart: cv-web-backend
    targetRevision: 0.0.10
    helm:
      values: |
        image:
          tag: "latest"
        ingress:
          host: dev-backend.andrefeuille.com
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
