services:
  # ******************
  # Temporal Server
  # ******************
  temporal:
    image: temporalio/auto-setup:1.24.1
    container_name: temporal
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
      - POSTGRES_SEEDS=postgres
      - TEMPORAL_DB=cv_web_temporal_db
    ports:
      - "7233:7233" # default gRPC port
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default

  # ******************
  # Temporal UI
  # ******************
  temporal-ui:
    image: temporalio/ui:latest
    container_name: temporal-ui
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - "8088:8080"
    depends_on:
      - temporal
    networks:
      - default
