apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "cv-web-backend.name" . }}-secrets
  namespace: {{ .Values.general.appNamespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "cv-web-backend.name" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD_APP # pragma: allowlist secret
      remoteRef:
        key: cv_web_dev/app_user_password
        property: password
    - secretKey: DB_PASSWORD_FLYWAY # pragma: allowlist secret
      remoteRef:
        key: cv_web_dev/app_user_flyway_password
        property: password
    - secretKey: DB_PASSWORD_TEMPORAL # pragma: allowlist secret
      remoteRef:
        key: cv_web_dev/app_user_temporal_password
        property: password
