apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cv-web-backend.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: "{{ .Values.general.certManagerIssuer }}"
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.general.nginxIpWhitelist }}"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "{{ .Values.general.cloudflareProxied }}"
    external-dns.alpha.kubernetes.io/access: public
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  rules:
    - host: {{ .Values.general.backendIngressURL }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cv-web-backend.fullname" . }}
                port:
                  name: http
