apiVersion: v1
kind: Service
metadata:
  name: {{ include "cv-web-backend.fullname" . }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: {{ include "cv-web-backend.name" . }}
