apiVersion: v1
kind: Service
metadata:
  name: {{ include "cv-web-backend.fullname" . }}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ include "cv-web-backend.name" . }}
