apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cv-web-frontend.fullname" . }}-nginx-config
  namespace: {{ .Values.general.appNamespace }}
  labels:
    app: {{ include "cv-web-frontend.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  nginx.conf: |
    log_format json '{'
                    '"time_local": "$time_local", '
                    '"remote_addr": "$remote_addr", '
                    '"remote_user": "$remote_user", '
                    '"request": "$request", '
                    '"status": "$status", '
                    '"body_bytes_sent": "$body_bytes_sent", '
                    '"request_time": "$request_time", '
                    '"upstream_response_time": "$upstream_response_time", '
                    '"http_referer": "$http_referer", '
                    '"http_user_agent": "$http_user_agent", '
                    '"http_x_forwarded_for": "$http_x_forwarded_for", '
                    '}';
    server {
        listen       8080;
        listen  [::]:8080;
        server_name  localhost;
        set_real_ip_from {{ .Values.general.podsRangeCIDR }};
        real_ip_header CF-Connecting-IP;
        client_max_body_size 50M;
        access_log /dev/stdout json;
        location / {
            root   /usr/share/nginx/html;
            try_files $uri $uri$args /index.html =404;
        }
        location /api {
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass {{ .Values.general.backendInnerUrl }}/api;
            proxy_read_timeout 120;
        }
    }