apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cv-web-frontend.fullname" . }}
  labels:
    app: {{ include "cv-web-frontend.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "cv-web-frontend.name" . }}
      name: frontend
  template:
    metadata:
      labels:
        app: {{ include "cv-web-frontend.name" . }}
        name: frontend
        istio: monitor
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: {{ include "cv-web-frontend.name" . }}
          image: "ghcr.io/andrislapins/cv-web-frontend:{{ .Values.general.frontendImageTag }}"
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 2048Mi
            limits:
              cpu: 500m
              memory: 5120Mi
