apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cv-web-frontend.fullname" . }}
  labels:
    app: {{ include "cv-web-frontend.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ include "cv-web-frontend.name" . }}
      name: frontend
  template:
    metadata:
      labels:
        app: {{ include "cv-web-frontend.name" . }}
        name: frontend
        istio: monitor
        sidecar.istio.io/inject: "true"
      annotations:
        checksum/config-common: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ include "cv-web-frontend.name" . }}
          image: "ghcr.io/andrislapins/cv-web-frontend:{{ .Values.general.frontendImageTag }}"
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: {{ .Values.general.backendInnerUrl | quote }}
          resources:
            requests:
              cpu: 100m
              memory: 2048Mi
            limits:
              cpu: 500m
              memory: 5120Mi
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d
            readOnly: true
          - name: nginx-cache-volume
            mountPath: /var/cache/nginx
            readOnly: false
          - name: nginx-cache-volume
            mountPath: /var/log/nginx
            readOnly: false
          - name: nginx-cache-volume
            mountPath: /var/run
            readOnly: false
      volumes:
      - name: nginx-config
        configMap:
          name: {{ include "cv-web-frontend.fullname" . }}-nginx-config
      - name: nginx-cache-volume
        emptyDir: {}