apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cv-web-frontend.fullname" . }}
  labels:
    app: {{ include "cv-web-frontend.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "cv-web-frontend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cv-web-frontend.name" . }}
    spec:
      containers:
        - name: {{ include "cv-web-frontend.name" . }}
          image: "ghcr.io/andrislapins/cv-web-frontend:{{ .Values.image.version }}"
          ports:
            - containerPort: 80
