apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cv-web-frontend.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: "{{ .Values.general.certManagerIssuer }}"
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.general.nginxIpWhitelist }}"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "{{ .Values.general.cloudflareProxied }}"
    external-dns.alpha.kubernetes.io/access: public
    cert-manager.io/acme-challenge-type: dns01
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  rules:
    - host: {{ .Values.general.frontendIngressURL }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cv-web-frontend.fullname" . }}
                port:
                  number: 3000
  tls:
    - hosts:
        - {{ .Values.general.frontendIngressURL }}
      secretName: {{ .Values.general.frontendIngressURL }}-tls
