apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: { { include "cv-web-frontend.fullname" . } }
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: { { .Values.ingress.host } }
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: { { include "cv-web-frontend.fullname" . } }
                port:
                  number: http
