apiVersion: v1
kind: Service
metadata:
  name: {{ include "cv-web-frontend.fullname" . }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ include "cv-web-frontend.name" . }}
