apiVersion: v1
kind: Service
metadata:
  name: {{ include "cv-web-frontend.fullname" . }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: {{ include "cv-web-frontend.name" . }}
    name: frontend
