apiVersion: v1
kind: Service
metadata:
  name: {{ include "cv-web-frontend.fullname" . }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: {{ include "cv-web-frontend.name" . }}
