global:
  resolve_timeout: 1m

route:
  receiver: cv-web-telegram
  routes:
    - match:
        severity: critical
      receiver: cv-web-telegram

receivers:
  - name: "cv-web-telegram"
    telegram_configs:
      - bot_token: xxx
        api_url: https://api.telegram.org
        chat_id: xxx
        parse_mode: ""
