global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: "prometheus-self"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "cv-web-backend"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["backend:8080"] # Original value: ['backend:8080']. Alert manager invoking value for testing: ['backend:1234']
  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
  - job_name: "otel-collector"
    static_configs:
      - targets: ["192.168.1.10:8888"]
  - job_name: "temporal"
    static_configs:
      - targets: ["temporal:7233"] # http://localhost:39793/metrics
