apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cv-web-frontend-app
  namespace: argo-cd
spec:
  project: default
  destination:
    namespace: cv-web-dev-ns
    server: https://kubernetes.default.svc
  source:
    path: argocd/dev/
    repoURL: https://github.com/andrislapins/cv_web.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - argocd/dev/cv-web-frontend-values.yaml
  syncPolicy:
    automated: {}
