general:
  appNamespace: cv-web-dev-ns
  backendHelmChartVersion: 0.1.6
  backendImageTag: 2025-04-28-2000-3cfae7a
  backendIngressURL: cv-web-api-dev.andrefeuille.com
  backendInnerUrl: http://cv-web-backend-dev-cv-web-backend:8080/
  dbHost: postgresql.cv-web-dev-ns.svc.cluster.local
  dbName: cv_web
  dbReset: 'false'
  dbUsernameApp: app_user
  dbUsernameFlyway: app_user_flyway
  flywayCleanDisabled: 'false'
  frontendHelmChartVersion: 0.1.16
  frontendImageTag: 2025-05-01-1500-d2f8818
  frontendIngressURL: cv-web-dev.andrefeuille.com
  temporalPort: 7233
  temporalUrl: temporal-frontend.cv-web-dev-ns.svc.cluster.local
