general:
  appNamespace: cv-web-dev-ns
  backendHelmChartVersion: 0.1.4
  backendImageTag: 2025-04-28-1700-733329b
  backendIngressURL: cv-web-api-dev.andrefeuille.com
  dbHost: postgresql.cv-web-dev-ns.svc.cluster.local
  dbName: cv_web
  dbReset: 'false'
  dbUsernameApp: app_user
  dbUsernameFlyway: app_user_flyway
  dbpasswordApp: app_user # pragma: allowlist secret
  dbpasswordFlyway: app_user_flyway # pragma: allowlist secret
  flywayCleanDisabled: 'false'
  frontendHelmChartVersion: 0.1.3
  frontendImageTag: 2025-04-12-1900-3c1fcbb
  frontendIngressURL: cv-web-dev.andrefeuille.com
  temporalPort: 7233
  temporalUrl: temporal-frontend.cv-web-dev-ns.svc.cluster.local
