general:
  backendHelmChartVersion: 0.0.16
  frontendHelmChartVersion: 0.0.21
  backendImageTag: 2025-04-12-1900-4a1c914
  backendIngressURL: backend-dev.andrefeuille.com
  frontendImageTag: 2025-04-12-1900-3c1fcbb
  frontendIngressURL: frontend-dev.andrefeuille.com
  certManagerIssuer: "cloudflare-issuer"
  nginxIpWhitelist: "80.89.77.186/32, 80.89.79.192/32, 95.216.197.156/32 65.109.162.225/32 157.180.30.61/32 172.16.0.101/32 172.16.0.102/32 172.16.0.103/32"
  cloudflareProxied: "false"
  flywayCleanDisabled: "false"
  dbReset: "false"
  dbHost: postgresql.cv-web-dev-ns.svc.cluster.local
  dbName: cv_web
  dbUsernameApp: app_user
  dbUsernameFlyway: app_user_flyway
  dbpasswordApp: app_user # pragma: allowlist secret
  dbpasswordFlyway: app_user_flyway # pragma: allowlist secret
  temporalUrl: temporal.cv-web-dev-ns.svc.cluster.local
  temporalPort: 7233
  appNamespace: cv-web-dev-ns