name: Helm Package and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "helm/**"
jobs:
  helm-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    defaults:
      run:
        working-directory: helm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: prepare - install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Package Helm Charts
        run: |
          helm package cv-web-backend
          helm package cv-web-frontend

      - name: Push Helm charts to GHCR
        run: |
          helm push cv-web-backend-*.tgz oci://ghcr.io/andrislapins/helm-charts
          helm push cv-web-frontend-*.tgz oci://ghcr.io/andrislapins/helm-charts
