name: Promote Images from DEV to PROD

on:
  workflow_dispatch:
  
jobs:
  promote-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Obtain a GitHub App Installation Access Token
        id: github-app-token
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
          echo "::add-mask::$TOKEN"
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Use the obtained token
        run: |
          curl -X POST \
            -H "Authorization: Bearer $TOKEN" \
            -H 'Accept: application/vnd.github.v3+json' \
            -d '{"context":"test","state":"success"}' \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout ArgoCD configs repo
        uses: actions/checkout@v4
        with:
          repository: andrislapins/cv_web
          token: ${{ env.TOKEN }}
          path: configs

      - name: Promote from DEV to PROD
        run: |
          cd configs
          git config --global user.email "hetzner-cloud-cv-web-gh-app[bot]@users.noreply.github.com"
          git config --global user.name "hetzner-cloud-cv-web-gh-app[bot]"
          sed -i "s/backendImageTag: .*/backendImageTag: $(grep 'backendImageTag:' ./argocd/dev/values.yaml | cut -d ':' -f2)/" ./argocd/prod/values.yaml
          sed -i "s/frontendImageTag: .*/frontendImageTag: $(grep 'frontendImageTag:' ./argocd/dev/values.yaml | cut -d ':' -f2)/" ./argocd/prod/values.yaml
          git add ./argocd/prod/values.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git remote set-url origin https://x-access-token:${{ env.TOKEN }}@github.com/andrislapins/cv_web.git
            git commit -m '[version bump]: for PROD'
            git push
          fi